[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
arc-swap.workspace = true
axum.workspace = true
base64.workspace = true
crossbeam-channel.workspace = true
domain.workspace = true
graph.workspace = true
hyper.workspace = true
hyper-util.workspace = true
market.workspace = true
route.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net"] }
tower = { workspace = true, features = ["util"] }
tower-http.workspace = true
tracing.workspace = true
tx.workspace = true

[dev-dependencies]
base64.workspace = true
bytes.workspace = true
dex.workspace = true
flate2.workspace = true
serde_json.workspace = true
stats_alloc.workspace = true
tokio = { workspace = true, features = ["io-util"] }

[lints]
workspace = true
